export const TASK_STRINGS = {
  errors: {
    load: 'タスクの読み込みに失敗しました',
    update: 'タスクの更新に失敗しました',
    updateStatus: 'ステータスの更新に失敗しました',
    updateDueDate: '期限の更新に失敗しました',
    updateAssignee: '担当者の更新に失敗しました',
    create: 'タスクの作成に失敗しました',
    delete: 'タスクの削除に失敗しました',
    bulk: '一括更新に失敗しました',
    bulkSelectTargets: '更新対象のタスクを選択してください',
    bulkSelectFields: '更新内容(ステータス/期限)を選択してください',
    titleRequired: 'タイトルは必須です',
    createTitleRequired: 'タスクタイトルを入力してください',
    createCompanyRequired: '会社を選択してください',
  },
  success: {
    update: 'タスクを更新しました',
    updateStatus: 'ステータスを更新しました',
    updateDueDate: '期限を更新しました',
    updateAssignee: '担当者を更新しました',
    create: 'タスクを作成しました',
    delete: 'タスクを削除しました',
    bulk: '一括更新しました',
  },
  labels: {
    section: 'タスク',
    pageTitle: 'タスク管理',
    totalCount: '総件数',
    scopeLabel: '表示範囲',
    scopeMine: '自分',
    scopeAll: '全件',
    scopeUser: '担当者',
    viewList: 'リスト',
    viewKanban: 'カンバン',
    searchPlaceholder: 'タスクを検索...',
    filter: 'フィルター',
    statusFilterLabel: 'ステータスで絞り込み',
    statusOption: 'ステータス',
    assigneeFilterLabel: '担当者で絞り込み',
    assigneeOption: '担当者',
    targetFilterLabel: '対象で絞り込み',
    targetOption: '対象',
    dueFrom: '開始日',
    dueTo: '終了日',
    dueFromPlaceholder: '開始日...',
    dueToPlaceholder: '終了日...',
    dueDate: '期限',
    dueDatePlaceholder: '期限...',
    assignee: '担当者',
    target: '対象',
    status: 'ステータス',
    actions: '操作',
    details: '詳細',
    title: 'タイトル',
    description: '説明',
    titlePlaceholder: 'タスクのタイトル',
    descriptionPlaceholder: 'タスクの説明',
    createTitle: 'タスクタイトル',
    createTargetType: '対象',
    createCompany: '会社',
    createAssignee: '担当者',
    createDescription: '詳細',
    createDueDate: '期限',
    createTitlePlaceholder: '対応内容を入力...',
    createTargetTypePlaceholder: '対象を選択...',
    createCompanyPlaceholder: '会社名で検索...',
    createDescriptionPlaceholder: '背景や補足を入力...',
    createDueDatePlaceholder: '期限...',
    unassigned: '未設定',
    filterSummary: '絞り込み:',
    keyword: 'キーワード',
    selectedCountSuffix: '件選択',
    selectTaskSuffix: 'を選択',
    statusForTaskSuffix: 'のステータス',
    assigneeForTaskSuffix: 'の担当者',
    dueDateForTaskSuffix: 'の期限',
  },
  confirm: {
    deleteTitle: 'タスクを削除しますか？',
    deleteConfirmLabel: '削除',
    cancelLabel: 'キャンセル',
    deleteDescription: (title: string) => `「${title}」を削除します。元には戻せません。`,
  },
  actions: {
    new: '新規作成',
    create: 'タスクを作成',
    createTitle: 'タスク作成',
    creating: '作成中...',
    edit: '編集',
    save: '保存',
    saving: '保存中...',
    clearAll: 'すべて解除',
    apply: '適用',
    backToList: '一覧に戻る',
    selectAll: 'すべてのタスクを選択',
  },
  messages: {
    notFound: 'タスクが見つかりませんでした。',
    emptyList: 'タスクが見つかりません。',
  },
  bulk: {
    statusLabel: 'ステータスを一括変更',
    dueDateLabel: '期限を一括変更',
    dueDatePlaceholder: '期限...',
    clearDueDateLabel: '期限をクリア',
    submitLabel: '一括更新',
  },
  empty: {
    adminAll: '全担当のタスクがまだありません。',
    normal: 'まずはタスクを追加して、対応状況を可視化しましょう。',
    readonly: '権限の設定を確認してください。',
  },
  hints: {
    filterFocus: 'フィルターにフォーカス',
  },
  panel: {
    createTitle: 'タスク作成',
    createDescription: '企業または未紐づけでタスクを追加できます。',
  },
  notices: {
    readonly: '権限がないため、タスクのステータス変更はできません。',
    readonlyDetail: '権限がないため、タスクの編集・削除はできません。',
  },
} as const
